apiVersion: v1
kind: Service
metadata:
  name: metadata-service-nodeport
  labels:
    app: metadata-service-app
spec:
  type: NodePort
  selector:
    app: metadata-service-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30006