apiVersion: v1
kind: Service
metadata:
  name: metadataservice-nodeport
spec:
  type: NodePort
  selector:
      type: back-end
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000