
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
    type: db
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongodb
      type: db
  template:
    metadata:
      labels:
        app: mongodb
        type: db
    spec:
      containers:
      - name: mongo-container
        image: mongo
        ports:
              - containerPort: 27017
        volumeMounts:
          - mountPath: /data/db
            name: test-volume
      volumes:
        - name: test-volume
          hostPath:
            # directory location on host
            path: /data