apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: metadata-service-replicaset
  labels:
    app: metadata-service-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: metadata-service-app
  template:
    metadata:
      labels:
        app: metadata-service-app
    spec:
      containers:
        - name: metadata-service-app
          image: sunitparekh/metadata:v2.0
          env:
            - name: MONGODB_URI
              value: mongodb://mongo/metadata
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
            initialDelaySeconds: 10
            periodSeconds: 5