apiVersion: v1
kind: Pod
metadata:
  name: metadata-service-pod
  labels:
    app: metadata-service-app
spec:
  containers:
  - name: metadata-service-pod
    image: luckyganesh/metadata-service:v1
    ports:
        - containerPort: 8080